site_name: pylogalert
site_description: "pylogalert: Python logging library with JSON output, ContextVar context, PII redaction, sampling, and EMERGENCY alerts (Slack, SES)."
site_url: https://jonrato.github.io/pylogalert/
repo_url: https://github.com/jonrato/pylogalert

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - sitemap:
      changefreq: weekly
      priority: 0.5
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_signature: true
            show_root_heading: true
            show_source: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jonrato/pylogalert


nav:
  - Home: index.md
  - Tutorial:
      - Quickstart: tutorial/quickstart.md
  - How-to:
      - Redaction: howto/redaction.md
      - Sampling: howto/sampling.md
      - Context: howto/context.md
      - Exceptions: howto/exceptions.md
      - Color (TTY/Dev): howto/color.md
      - Timezone: howto/timezone.md
      - EMERGENCY & Channels: howto/emergency_channels.md
      - Advanced Notifier: howto/notifier.md
  - Reference:
      - API: reference/index.md
  - Explanation:
      - Design & Concepts: explanation/design.md
  - Contributing: contributing.md